### ISSUE TITLE
how does one use promises in data loading?

### ISSUE THREAD

**Issue by TerraSkye** [webonyx/graphql-php#118]
the title says it all, how should i use promises loading data? 
so that i will make 1 query call ```select * from blog where id in (...)```
 instead multiple
 ```select * from blog where id = ...```
?

**Comment by vladar** [comment]
If you need out-of-the-box solution, check out [DataLoader](https://github.com/overblog/dataloader-php#using-with-webonyxgraphql), otherwise you will have to write your own batch loading functions/classes. 

Example is described in http://webonyx.github.io/graphql-php/data-fetching/#solving-n1-problem Please let me know what is not clear for you in these docs?

**Comment by TerraSkye** [comment]
Thnx that satisfied my needs
