### ISSUE TITLE
[v15] Psalm errors about uninitialized fields when extending types.

### ISSUE THREAD

**Issue by TJ09** [webonyx/graphql-php#1309]
When extending many of the type classes (e.g. `InterfaceType`, `ObjectType`), Psalm gives errors that a number of fields are not initialized by the constructor. This is correct: these fields are intentionally not initialized with a value e.g. https://github.com/webonyx/graphql-php/blob/master/src/Type/Definition/HasFieldsTypeImplementation.php#L17.

Rather than using `isset` with no default value, can these cases perhaps default the property to null instead? This should allow lazy initialization to continue to work while allowing projects using this library to extend type definitions without errors.

**Comment by spawnia** [comment]
These fields should be non-nullable though - assigning `null` to them is not right. I believe you can disable this Psalm analysis.

**Comment by TJ09** [comment]
The rule can be disabled, but it means disabling it project-wide. I don't believe I can choose to be notified of uninitialized properties in my own code and ignore only the errors coming from properties in graphql-php.

I'm not sure I understand the problem with a value of null meaning "not initialized" in the exact same way `isset($this->fields)` is used now?

**Comment by shmax** [comment]
> I'm not sure I understand the problem with a value of null meaning "not initialized" in the exact same way isset($this->fields) is used now?

The only way phpstan (and modern versions of PHP) will tolerate initializing a member to to `null` is if the annotations on the member allow for `null` as one of the possible types. If we do that, then we wind up in the position of having type annotations that are not correct (because we don't want to allow `null` writes at any time after initialization). Psalm's notion of catching variables that aren't initialized in the constructor is a little half-baked, as there is no semantic rule in the language (or any language that I can think of) that requires the practice; I suspect they implemented the rule that way because it seemed like a sexy feature and it was easier than tracking the state of the member throughout analysis. In any case, we've talked about this kind of thing at length before and would rather not weaken the typing of our members solely for the benefit of Psalm. At this point I think your best bet will be to take it up with the authors of Psalm.

**Comment by TJ09** [comment]
> as there is no semantic rule in the language (or any language that I'm familiar with) that requires the practice

PHP throws if you access a property that hasn't been initialized (if it has a typehint), and it's non-trivial to statically guarantee all reads will happen only after initialization. Hack/HHVM actually do have the same behavior.

Nonetheless, thanks for your explanation and for the consideration. I'll take this into account and deal with it from my end.
