### ISSUE TITLE
Lazy Loading of types is missing a full loading method

### ISSUE THREAD

**Issue by mcg-web** [webonyx/graphql-php#168]
While trying to introduce lazy loading in the [overblog/graphql-bundle](https://github.com/overblog/GraphQLBundle), the exception (`GraphQL\Error\InvariantViolation: Could not find possible implementing types for Node in schema. Check that schema.types is defined and is an array of all possible types in the schema.`) is throw when combining types lazy loading and `assertValid. This exception is throw because when using typeLoader there's no existing method to fully load all types. Here an example:

```graphql
interface Node {
  id: ID!
}

type Query {
   node(id: String!): Node
}

type Ship implements Node {
   id: String!
   name: String
}

type Ship implements Node {
   id: String!
   name: String
}

type Faction implements Node {
   id: String!
   name: String
}

schema {
  query: Query
}
```

**Comment by vladar** [comment]
Actually `assertValid` loads all types it can extract from the schema (by calling `getTypeMap()`) internally. 

This exception will also happen without lazy-loading because you can't infer all existing types from this schema.

For example, if you start scanning from the Query type, you can only find `Node` and `String`. With such schema, you must register all remaining types in `types` option of the schema.

One way to combine `types` option with lazy-loading is to pass `types` as a Closure. It is only called when loading the whole schema (e.g. by `assertValid`) and won't be called for regular queries.

**Comment by mcg-web** [comment]
That the idea @vladar :+1: for this solution :)

**Comment by vladar** [comment]
@mcg-web Yeah, we use it in BuildSchema to create schema from type language. So take a look at this [piece of code](https://github.com/webonyx/graphql-php/blob/master/src/Utils/BuildSchema.php#L244) for reference.

**Comment by mcg-web** [comment]
thank you @vladar this fix it!
