### ISSUE TITLE
How to replace internal types?

### ISSUE THREAD

**Issue by danez** [webonyx/graphql-php#174]
We use our own IDType because our ids are represented as stringable objects in PHP code.

This worked fine till I tried to upgrade from 0.9 to 0.11.

Now we get this error:
```
[GraphQL\Error\InvariantViolation]                                           
Schema must contain unique named types but contains multiple types named "ID" (see http://webonyx.github.io/graphql-php/type-system/#type-registry).    
```

This happens because the internal types are always registered and added to the resolved types. We would have at least thought that when supplying the `typeLoader` it works, but the internal types are still loaded.

Is there a proper way to not have graphql-php initialize the default types or at least the ID type?

**Comment by vladar** [comment]
Yeah, the reason is that we don't scan type fields when using lazy type loading. So internal types were added explicitly on schema creation. 

I just implemented a workaround where you can override internal types using `types` option of the schema. It should be available in v0.11.1 (just published). 

Please try it when you have a chance.

**Comment by danez** [comment]
Thank you very much for the quick response, I will test now.

**Comment by danez** [comment]
Worked perfectly
