### ISSUE TITLE
How to resolve a field value from other field's sub-filed?

### ISSUE THREAD

**Issue by wengjs** [webonyx/graphql-php#196]
Hello,

I got a data structure like this:
```
{
	boards {
		id,
		name,
		last_updated_at,
		childs {
			id,
			name,
			last_updated_at
		}
	}
}
```
Childs will resolve from DB query where board_id equal parent id.

I want to resolve last_updated_at which under boards equal the most current childs' last_updated_at.

There are 4 variables pass into resolve function.
```
function ($value, $args, $context, $info)
```
How do I use them to get what I need?

**Comment by vladar** [comment]
There are lots of ways to do this. But it depends on constraints of your data structure.

Some variants:
1. Do a separate SQL query for this field
2. Fetch same children as in "childs" field (but use some data caching layer to avoid double fetching)
3. Use a getter for "childs" which saves the result in BoardEntity class
4. Prefetch children in parent field and include it in your BoardEntity class so that $value->childs always returned same children

etc, etc. This is your app logic after all.

**Comment by wengjs** [comment]
:sob:

**Comment by vladar** [comment]
Not really an issue, so closing. But feel free to ask more question if needed.
