### ISSUE TITLE
Arguments for field resolvers

### ISSUE THREAD

**Issue by crirus** [webonyx/graphql-php#205]
Hello

I have a resolver for a field in QueryType which receive the arguments just fine.
However, this top type also have a list of subtypes. Imagine UserType with list of friends.
How do I pass the arguments sent in query to resolver of friends?
I'd like to be able to filter friends list as well, not just the users, using part of those arguments

Thanks.

**Comment by crirus** [comment]
Should not be a big deal, basically I have a resolver for Query Type where I get the arguments, then I have multiple other resolvers for each field where I don't get arguments received from client.

Would be nice to be able to access them anywhere natively.

**Comment by crirus** [comment]
Here is a query I am working on
```
query {
  operatingSystems(
    filter:{
      field:name,
      type:LIKE
      value:"Andro"
      versions:{
        field:version
        type:LIKE
        value:"update"
      }
    }
  ){
  id
  name
    versions{
      id
      version
      osId
    }
  }	
}
```

**Comment by vladar** [comment]
This is not how GraphQL works. If you need arguments in the specific field - just pass arguments on that level in the query:

```graphql
query {
  operatingSystems(
    filter:{
      field:name,
      type:LIKE
      value:"Andro"
    }
  ){
  id
  name
    versions (filter: { versionFilter: "something" }) {
      id
      version
      osId
    }
  }	
}
```

Otherwise, it is your responsibility to pass these values down the query. Options are:
1. Since you rely on those to resolve nested field - include them in the value returned by parent resolver
2. Use context to pass it to the deeply nested resolvers

But both of those methods are not recommended. The recommended one is to pass arguments directly to the field that needs them.

**Comment by crirus** [comment]
Ohh, I tried that, was the first logical idea, but I misplaced the args, instead having them in OperatingSystemType, I put them in OperatingSystemVersionsType, one level too deep.

Thanks for the hint this solved this whole nested args issue that I had, gracefully.
