### ISSUE TITLE
DocumentValidator bottleneck

### ISSUE THREAD

**Issue by enumag** [webonyx/graphql-php#269]
I'm profiling my application using Blackfire. Right now around 25% of the time to response is consumed by `\GraphQL\Validator\DocumentValidator::validate()`. This is quite a lot. I need some way to either significantly reduce the validation time or to cache the result for the same requests in the future to avoid running the validation again.

I don't think reducing the validation time is possible - or not by much. Caching the result should be possible but from the code this doesn't seem to be supported at the moment. Can you give me some advice how to implement it?

It's not necessary to cache the result of a request with errors, those will be rare and can be slow. No need to fill the cache. But normal successful requests need to be as fast as possible and this slows them down significantly.

**Comment by vladar** [comment]
You can implement caching logic in your app.

If you know that the query is valid just pass an empty array of validation rules.

**For the Standard Server:**
See [`validationRules` option](http://webonyx.github.io/graphql-php/executing-queries/#server-configuration-options).

**For the `GraphQL::executeQuery` facade method:**
Pass a custom set of validation rules in the [last argument](http://webonyx.github.io/graphql-php/executing-queries/#using-facade-method).

There is also an entry in doc which is not directly related, but which may be useful: http://webonyx.github.io/graphql-php/executing-queries/#custom-validation-rules

In general the most performant solution is to use persisted queries. With a standard server you can enable them by setting `persistentQueryLoader` and setting `validationRules` as a callable (see clarifications on options).

The idea of persisted queries is that you save your queries somehow on the server and get `queryId` which you later use on the client instead of `query`. Then on the server you store cached AST of the query and disable validation. This way you bypass both parsing and validation steps for a query.

**Comment by enumag** [comment]
This looks promising. I'll try it next week and post here what I end up with. Thank you!

**Comment by vladar** [comment]
Cool, feel free to re-open if needed.

**Comment by vladar** [comment]
You want to use version v0.11.6 (just released) as it has some performance improvements for the case with an empty list of validation rules.
