### ISSUE TITLE
Can I build shema object from introspection string?

### ISSUE THREAD

**Issue by arkonchik** [webonyx/graphql-php#293]
I founded that i can build schema object from sdl, but can I build shema object from introspection string?

**Comment by vladar** [comment]
At the moment - no. We didn't port [`buildClientSchema`](https://github.com/graphql/graphql-js/blob/master/src/utilities/buildClientSchema.js) from the reference implementation, because it has way less value for the server implementation (even the name of the utility suggests this).

I guess we could accept a PR for it, but any utility has a maintenance cost. So I am curious what is your use case? Why do you need it?

**Comment by arkonchik** [comment]
Thanks for the answer.
I have a service that save graphql queries([persisted queries](https://dev-blog.apollodata.com/persisted-graphql-queries-with-apollo-client-119fd7e6bba5)) 
Before it saves the query it could try to validate them by introspection.
In this case i can try to validate this queries before save in gitlabci stage with javascript

**Comment by spawnia** [comment]
This would be a useful feature for any GraphQL client in PHP. I am currently building one and realized that graphql-php does not support it yet, see https://github.com/spawnia/sailor/issues/2

@vladar where would you add that functionality, does it belong in `BuildSchema::buildClientSchema`?

What would be the simplest way of implementing it? I am thinking of adding a transformation step from JSON into an AST and then pass that to `BuildSchema::buildAST`.

**Comment by vladar** [comment]
I would strongly recommend to port [buildClientSchema](https://github.com/graphql/graphql-js/blob/master/src/utilities/buildClientSchema.js) directly from the reference implementation into the new utility class `BuildClientSchema` along with all the related tests.

Primarily because it is way easier to maintain it this way and keep in sync with the reference implementation.
