### ISSUE TITLE
throwing GraphQL\Error\UserError: HTTP 400

### ISSUE THREAD

**Issue by baversjo** [webonyx/graphql-php#309]
Hello,

In a previous version from april ( tree https://github.com/webonyx/graphql-php/commit/ec0985619f ),
throwing a `GraphQL\Error\UserError` would return the error in the http response per graphql standard, with HTTP 200.

However, when I upgraded to a recent version of dev-master (https://github.com/webonyx/graphql-php/commit/82b1dbd836 ) throwing a UserError would cause http 400 bad request instead (still with the error in the body).

My understanding is, that per graphql standards, user errors should still return http 200 but with the error in the http body? Is this a bug, or was this change intended behavior in `graphql-php`? I looked through the changes and while there's been a lot, there's nothing obvious that would indicate this change: https://github.com/webonyx/graphql-php/compare/ec0985619f...82b1dbd836

**Comment by vladar** [comment]
This is likely a bug. Can you provide a smallest possible test case on how to reproduce it?

**Comment by jsiebern** [comment]
I can confirm this problem. Reproduction is fairly easy, just use **any** schema / resolver schema (at least for me) and throw an error like so:
```php
throw new \GraphQL\Error\UserErrorUserError('Any error');
```

This will return an http response with the code 400 instead of 200 which makes Apollo (as an example) not pick it up properly!

**Comment by jsiebern** [comment]
The issue seems to be here:

https://github.com/webonyx/graphql-php/blob/392b567f235a528539f47e8c501f2daed029adeb/src/Server/Helper.php#L480

Where it probably should be `empty` instead of `!empty` ?

**Comment by vladar** [comment]
Initially, this server was supposed to mirror express-graphql logic. And they return status code 500 in such case ([here](https://github.com/graphql/express-graphql/blob/master/src/index.js#L330)).

So status 400 is obviously invalid. But the question is if we should switch to Apollo-style and return 200 or be compatible with express-graphql and return 500 (which is also more semantically correct for HTTP in case of execution errors).

**Comment by jsiebern** [comment]
I'd say the context of HTTP protocol it makes sense to send status 4 / 500. But in a GraphQL Context it makes sense to send 200 as the call itself has passed and the graphql implementation expects the client to handle those errors, there's no need to indicate it with another status (which apollo makes quite clear by failing on a not 200 code and not displaying the actual errors).

To sum it up: I think 200 makes more sense as it reflects GraphQLs intention of leaving the client to deal with a **GraphQL** error (as the request itself has been handled perfectly well and therefore deserves a 200).

Sorry for my confusing writing, I hope my reasoning makes some sense.

**Comment by mfn** [comment]
What is the authority on the expected behaviour here, regarding HTTP status code?

I'm a GraphQL newcomer but immediately noticed this … incoherence? … regarding payloads/status codes. But the "specs" ( http://facebook.github.io/graphql/June2018/ ) don't mention anything regarding this (or I missed it).

**Comment by vladar** [comment]
Related: working draft of the graphql-over-http spec: https://github.com/APIs-guru/graphql-over-http

**Comment by OssiPesonen** [comment]
> If the data entry in the response has any value other than null (when the operation has successfully executed without error) then the response should use the 200 (OK) status code. If the operation failed before or during execution, due to a syntax error, missing information, validation error or any other reason, then response should use the 4XX or 5XX status codes. It is recommended to use the same error codes as the reference implementation.

I just stumbled into this when I created a middleware to check for a `@signed` directive that verifies if the GraphQL request contains an access token. If it's not present the middleware throws an exception (client safe) before the resolver is called. This results in a 400 Bad Request because of the simple nature of the error check (data is null and error is present). Per HTTP status codes it should throw a 401 Unauthorized, not 400 Bad Request. 

I would say if we were to use any codes from range 400-499 we should check the category of an error. I've accustomed to use string versions of the HTTP status codes ie. `UNAUTHORIZED` of `FORBIDDEN`. This could just as easily be an implementation of the library, and we could provide some `GraphQL\Error\Category` namespace constants such as `Code::UNAUTHORIZED` (just from the top of my head).

However, I would say leave it at 200 OK. This is simply because I believe Apollo reads anything but 200 as a network error and you can't access the request body. This causes problems on the front-end side of things.

**Comment by swashata** [comment]
It would be great, if we could at least configure the status code of `StandardServer` http status code in case there's a ClientAware exception to 200. This way, the errors would be visible to `apollo-client` package and we don't have to write our own servers.
