### ISSUE TITLE
Performance: Is there a way to cache the Schema?

### ISSUE THREAD

**Issue by topikito** [webonyx/graphql-php#310]
Hi,

Ive read a few issues, all quite old, about performance issues and how to address them. There does not seem to be an up-to-date solution, so Im opening this issue for an update on how fixing performance today looks like.

The issue Im experiencing is that it takes around 6 seconds to instantiate the `Schema` object. Ive read about way to improve it [here](http://webonyx.github.io/graphql-php/type-system/schema/#lazy-loading-of-types) but I was wondering if there was another simpler way?

Maybe getting exporting a Schema to an AST and caching it?

Thanks

**Comment by topikito** [comment]
Just want to add that this has nothing to do with an issue with the library itself, but is more a question regarding ways I can improve my use case. May this be by caching the Schema, etc…

**Comment by vladar** [comment]
How do you initialize your schema? If you use schema language, have you read [this in docs](http://webonyx.github.io/graphql-php/type-system/type-language/#performance-considerations)?

Anyways, it's really hard to help you without some code. Ideally a reproducible example.

**Comment by topikito** [comment]
Thanks for the fast response.

Yes, thanks, Ive seen about Schema Language, really appropriate!

Ive edited the title now. My concern is more about being able to cache the resulting map when generating the queries and mutations and injecting them into the schema, kind of the same way Symfony would cache the routing to speed up initialisation of the app. I tried doing a `var_export` of the `Schema` after being initialised, but its way too big (memory issue).

**Comment by vladar** [comment]
If you use Schema Language and cache resulting AST (as [suggested in docs](http://webonyx.github.io/graphql-php/type-system/type-language/#performance-considerations)) and then using `BuildSchema` tool - you shouldn't have any performance issues even with large schemas.

`BuildSchema` produces a lazy schema by default. It only constructs types on demand during a query execution (unless you do schema validation or some other operations which perform full schema scan).

This is the most performant way to do this. There are some other possible tweaks, but they are mostly for memory savings, not performance.

So your issue is probably specific for your case. And in order to help you, I need to see some code example of how you use it.

**Comment by topikito** [comment]
Thanks @vladar - Ill take your comment in consideration.

I guess this closes my question/issue.
