### ISSUE TITLE
[BUG] Input type default value not set

### ISSUE THREAD

**Issue by yaquawa** [webonyx/graphql-php#350]
Hi 
Thanks for the great work!!

I'm using **version : ^0.12** of graphql-php

and I found that seems like the **default value** of input type won't work.

For example:
```graphql
input Condition {
    key: String!
    value: String!

    # This field won't be given as a argument if omit it in the query.
    operator: Operator = "eq" 
}
```

Hope this can be fixed.👍🏼

**Comment by vladar** [comment]
Default values for input type fields are not supported in the reference implementation [yet](https://github.com/graphql/graphql-js/issues/385). They must implement it first.

At the moment you have to define defaultValue at the field level of your parent object type. And it provides some ambiguity which has to be described in the spec first.

**Comment by yaquawa** [comment]
@vladar Thank you for checking this! Got it!

**Comment by yaquawa** [comment]
@vladar 
I think the spec already said the input object field can have a default value!
https://facebook.github.io/graphql/June2018/#InputFieldsDefinition

**Comment by vladar** [comment]
I've posted a link in my first reply where you can track this. I suggest re-opening it after related spec updates are published.

**Comment by spawnia** [comment]
@yaquawa i think i stumbled upon the issue you were having, from the looks of it while working on the same thing 😉 

What i found is that the `EnumType` expects the default value to be set to the internal value. Since we construct the args straight from the schema definition, we have to lookup the internal value - i am about to fix that in Lighthouse.
