### ISSUE TITLE
[Question] How to solve N+1 problem?

### ISSUE THREAD

**Issue by yaquawa** [webonyx/graphql-php#359]
Hi
I'm reading the following docs:

http://webonyx.github.io/graphql-php/data-fetching/

```php
'resolve' => function($blogStory) {
    MyUserBuffer::add($blogStory['authorId']);

    return new GraphQL\Deferred(function () use ($blogStory) {
        MyUserBuffer::loadBuffered();
        return MyUserBuffer::get($blogStory['authorId']);
    });
}
```

I've read it again and again, just can't understand how the `GraphQL\Deferred` works (what is the `MyUserBuffer` in the above code? ) and how to write code to prevent N+1 problem.

Would you please provide me a more detailed sample code?
Thanks very much!

**Comment by simPod** [comment]
Just gather all your ids in buffer:

`MyUserBuffer::add($blogStory['authorId']);`

As `return new GraphQL\Deferred(`* is returned, no actual data are returned yet from resolver.

All your resolvers would have returned Deferred for now (*) -> no data, just promises

In the end, when the `Deferred` promise is resolved, `get()` method on buffer is called.

In the buffer, you should check if there are any data available and if not, fetch all the data for all the ids in the buffer (eg. for database -> here you do only one query for all ids). Store the data in the buffer (**) and return only that for requested id.

Then every consecutive `get()` would again check if data are available (true cuz (**)) and again return only that for requested id.

**Comment by vasily-kartashov** [comment]
I wrote a simple BatchProcessor that may help you to deal with this https://github.com/vasily-kartashov/graphql-batch-processing

In your case you would use it like following

```
'resolve' => function($blogStory) {
    return Batch::as('usersByAuthorIds')
        ->collectOne($blogStory['authorId'])
        ->fetchOneToOne(function ($authorIds) {
            // here comes a repository method that returns a map from userId into User record
            return $userRepository->findUsersByUserIds($userIds);
        });
}
```

**Comment by akomm** [comment]
@yaquawa when the vendor logic (webonyx) goes through the resolve functions you define in your code and execute them, it checks for Deferred returned and when it finds one, it does not take it as a result, but collect it in a list. When it is done it execute the resolve logic of the Deferred (the closure/lambda). The closure has in some way access to a cache/collection (your apps logic) where you collected all the userIds. In the example case it is the MyUserBuffer you previously filled with ids. At this point you have all the Ids in the buffer when the deferred is executed. Then you can fetch all users using something like ->findUsersByUserIds in a single query. It is though important that the order of the ids passed to the Deferred resolve returns the actuall users in the same order as the passed ids, so the vendor logic (webonyx) can properly map the result to each location in the resolve graph it was previously running through.

**Comment by mfn** [comment]
Sorry to jump in, but I've a question regarding this:
> MyUserBuffer::add($blogStory['authorId']);

This is kinda the textbook example :-) But no one really would use static method aka global function for that, would we?

So usually you would use something which only exists for the live-cycle of the current GraphQL request, which is destroyed afterwards i.e. temporary buffer (like, for example, the `$context` passed? just wondering).

Are there any best practices how this is done in real code without polluting some global structure? I understand it's easiest this way because due to it's global nature you don't have to solve the problem of "passing the context with the collected ids around until it's resolved" (there, "context", I said it again).

Thanks!

**Comment by simPod** [comment]
@mfn use a service for that injected via DI from your container

Then call `$yourBufferService->add()` ;)

**Comment by vladar** [comment]
@mfn You are right, but this is just an illustration to focus on the main point.

In the real-life, you would use some external service injected to your type definition one way or another.

**Comment by mfn** [comment]
> use a service for that injected via DI from your container
…
> some external service injected to your type definition one way or another

When I use this approach, I still need to use a global singleton, otherwise how would I be able to access the same instance from different places. In that regard I could as well use the `StaticBufferClass::` approach.

Is it a _good practice_ to e.g. bind this to the `$context` being passed around? I would like to use something which is more tied to the GraphQL resolving life cycle than the whole request (think about long living PHP processes via react/swoole).

Thanks!

**Comment by vladar** [comment]
> When I use this approach, I still need to use a global singleton, otherwise how would I be able to access the same instance from different places

Not sure why do you need a singleton? Just inject it via type definition constructor (or some setter). It is a regular dependency injection stuff. Alternatively, yeah, you could put those instances to context.
