### ISSUE TITLE
Change errors to comply with spec recommendations?

### ISSUE THREAD

**Issue by nagledb** [webonyx/graphql-php#389]
The [Errors section of the June 2018 spec](https://facebook.github.io/graphql/June2018/#sec-Errors) recommends that `errors` entries contain only `message`, `locations`, `path`, and `extensions`. While other entires are currently permitted, they are discouraged; the spec recommends putting other entries in `extensions` instead.

The library currently adds `category`, `debugMessage`, and `trace` to entries. Would a PR be welcome to move them under `extensions` instead? If so, would it need to be configurable as to which location they go (to support backwards compatibility)?

**Comment by vladar** [comment]
Yeah, you are totally right. We added our custom entries to error when there was no specification for `extensions`. Now that they added it we'll have to adjust. But that would be a breaking change, so we'll introduce it in 14.0

**Comment by vladar** [comment]
Actually we already have a breaking change about extensions, so I decided to include this in the 0.13 release. But only `category` key will move under extensions.

`debugMessage` and `trace` will stay at the top level because they are not intended for production and the UX of debugging with those items moved under `extensions` will degrade significantly.

**Comment by nagledb** [comment]
That makes sense to me. Thanks!
