### ISSUE TITLE
executeAndReturnResult deprecation - breaking change

### ISSUE THREAD

**Issue by KevinAsher** [webonyx/graphql-php#433]
There's a breaking change while migrating from `executeAndReturnResult` to `executeQuery`, at this [line](https://github.com/webonyx/graphql-php/blob/master/src/GraphQL.php#L242) the `$promiseAdapter` is obtained from the `Executor` class, which the promise adapter can be set by third parties library like @mcg-web DataLoader (related issue #150). At this [line](https://github.com/webonyx/graphql-php/blob/master/src/GraphQL.php#L87) we can see the promise adapter is instantiated directly instead of using from the Executor class. I guess the easy fix is to just update `executeQuery` to use `Executor::getPromiseAdapter()` instead? This issue occured while updating [laravel-graphql](https://github.com/Folkloreatelier/laravel-graphql) to this [commit](https://github.com/Folkloreatelier/laravel-graphql/commit/deadb7e225ca2e0b944402d90a2844174e47746b).

**Comment by vladar** [comment]
Yes, this was a breaking change. But it was intentional. We had to ensure that `executeQuery` always returned `ExecutionResult` and never returned a promise. A counterpart method `promiseToExecute` was added which always returned a promise, but also accepted a promise adapter as an argument.

We should have added a note in UPGRADE.md about it though. Feel free to send a PR with such a note.

The change you propose will introduce another breaking change and will get us back to the mess with multiple possible return types (`array | Promise<array>`) which is something we'd like to avoid.
