### ISSUE TITLE
writing to php://output on resolve level? (streaming output)

### ISSUE THREAD

**Issue by kinimodmeyer** [webonyx/graphql-php#459]
hello together,

is there a way where you can partially generate the json and write it to the "php://output".

when i take this example https://github.com/webonyx/graphql-php/blob/master/examples/00-hello-world/graphql.php it waits for the whole process and at the end it return of all the json from GraphQL::executeQuery.  

is there a way we could write to php://output on maybe resolve-function level?
(then the client can start transfering and dont have to wait for whole process to be finished)

**Comment by vladar** [comment]
At the moment there is no such way. And I am not sure if it makes sense for a GraphQL API. Streaming makes sense for huge JSON files. But GraphQL responses should be small and focused (the whole intent of GraphQL is to return what is needed only). I doubt that it would give significant performance improvements that will justify the added complexity.

There are some experiments though on adding streaming and deferring into GraphQL spec itself (see [this post](https://blog.apollographql.com/new-features-in-graphql-batch-defer-stream-live-and-subscribe-7585d0c28b07)).

It is highly likely that it is a way to go in future instead of json streaming.
