### ISSUE TITLE
Directive with complex condition

### ISSUE THREAD

**Issue by Siregacvek** [webonyx/graphql-php#485]
Hello.
Issue:
I think it's a common case when you need different fields of the same entity for different pages. Very soon after start using GraphQl I started using fragments to have reusable queries. But then I stumbled a problem: my standard fragment contains many fields and many of them are not necessary on some pages. 
I found only one solution to make my fragment more flexible - directive `@include`. It's exactly what I need, but it's very limited because I can pass only one variable there and I can use only one `@include` directive at once. Because of this limitation this feature looks useless for me.
Proposition:
May be it's good for the bundle if we add the other one directive which can accept more complex conditions? Something like this:
```
{
  entity {
    name @complex_include(if: true or: false and: $boolVar)
    ...
  }
}
```
In ideal I think that it would be great to create 2 interfaces: `IncludeDirectiveInterface` and `SkipdirectiveInterface` so the user will be able to create a custom directive which will be respected in `ReferenceExecutor::shouldIncludeNode`.

In my project I already implemented the simple new directive which is doing what I need. If you feel that it's good for `graphql-php` project, I can create PR.
Or may be I solved my problem in a wrong way and there is something better?

**Comment by vladar** [comment]
I don't think such directive belongs in the core lib because it is non-standard. GraphQL is a spec first and it defines execution mechanics to ensure compatibility of various systems implementing the same spec. `@include` and `@skip` directives are part of the spec and this is the only specified method to remove fields from the result.

See, some UI framework may be relying on those directives to update its underlying cache. In all other cases, those frameworks may expect the field to exist in the result, while with your custom directives they won't be there which breaks the GraphQL contract.

Of course, you can break the spec in your own code, but it is not a good practice for the core lib. In general, custom directives shouldn't affect execution internals (anything that could be done in resolvers is fine though).

Also, I am not sure why you can't still use `@include` or `@skip` directive. Your `if` expression is still evaluated to boolean eventually, you just want to do it on the server. I don't see why this should be moved to the server vs the client?

You could create a separate variable for your field inclusion like this:

```graphql
query MyQuery($shouldInclude: Boolean!) {
  entity {
    name @include(if: $shouldInclude)
  }
}
```

And then evaluate the same expression on the client vs the server?
```javascript
query(MyQuery, { variables: { shouldInclude: (a && b) || c } })
```

**Comment by Siregacvek** [comment]
@vladar thanks for you suggestions. I agree that it's better to make these condition validations on client side.
I'm a backend dev and look on everything from backend-side).
