### ISSUE TITLE
Use case for nonNull arguments with defaultValue

### ISSUE THREAD

**Issue by vasily-kartashov** [webonyx/graphql-php#499]
What's the reason for having a non-nullable argument with default value as shown here: https://webonyx.github.io/graphql-php/type-system/input-types/#using-input-object-type

Skipping the argument results in an error, setting it to null as well. Under what circumstances does the `defaultValue` kick in?

**Comment by vladar** [comment]
I guess you are right and this is an error in docs. It shouldn't be `nonNull`.

**Comment by vladar** [comment]
Should be fixed, thanks!

**Comment by peldax** [comment]
Hello @vladar @vasily-kartashov ,
I want to have my parameters optional (with default value), but when provied, the value should not
be allowed to be Null. Currently this is not possible without additional userland check for null value.

What I understood in the GraphQL specs is that:
> if the argument has default value -> it is optional argument.

Whether the argument is nullable or not doesnt have anything to do with it being required/optional.

## Example:
### Definition with nullable argument
```
type Query {
  hero(arg: Argument = 1000) : Hero
}
```

#### Request
```{ hero { name } }```
Everything is alright - default value is used.
#### Request
```{ hero(arg: null) { name } }```
Incorrect - I do not want Argument to be null

### Definition with not-nullable argument
```
type Query {
  hero(arg: Argument! = 1000) : Hero
}
```

#### Request
```{ hero(arg: null) { name } }```
Everything is alright - disallowed null value to be passed into argument.
#### Request
```{ hero { name } }```
Error - Required argument is not provided.

**Comment by peldax** [comment]
After I re-read the specs I figured this statement:

> if the argument has default value -> it is optional argument.

is not fully correct - its more complicated than that. What I understand now is that you have defined set of arguments, each with its name, type and a default value (which is implicitly null) - for simplicity, lets just pretend we have one argument - and following behaviour:

- When the argument is not provided, doesn't have default value specified and is nullable -> use implicit null for this argument - typecheck is satisfied
- When the argument is not provided, doesn't have default value specified and is not nullable -> error: cannot pass default null into argument - argument is required, because otherwise the typecheck is not satisfied
- When the argument is not provided, does have default value specified and is nullable -> use default value for this argument, which has to match the type
- When the argument is not provided, does have default value specified and is not nullable -> use  default value for this argument, which has to match the type (cannot be null)
- When the argument is provided, doesn't or does have default value specified and is nullable -> use the value, which has to match the type
- When the argument is provided, doesn't have default value specified and is nullable -> use the value, , which has to match the type (cannot be null)

**Comment by peldax** [comment]
In file `ProviededNonNullArguments:36` adding ```$argDef->defaultValueExists()``` into condition solves the issue. 

But it is needed to validate the type of default arguments - I can simply declare string to be default value of list argument.
