### ISSUE TITLE
[Question] How do I get the request object in the context function?

### ISSUE THREAD

**Issue by MidnightDesign** [webonyx/graphql-php#512]
I want to add things like the current user and the user's language to the context by grabbing some values from the HTTP request headers. But when I set a context function (using `$serverConfig->setContext(function() { ... })`), that function only receives instances of `OperationParams`, `DocumentNode` and the operation type, but nothing that gives me access to the current `ServerRequestInterface` object.

I took a look at how this is done in apollo, and it [passes an object containing the request to the context function](https://www.apollographql.com/docs/apollo-server/features/authentication/#putting-user-info-on-the-context).

**Comment by mfn** [comment]
You don't need to make it a callable.

You can set it to anything (a class/object) on your own, initialized with whatever you need, having access to whatever you need.

Somewhere in your app / controller / etc. you call `\GraphQL\GraphQL::executeQuery` and as the 4th arg you simply pass whatever you will need.

**Comment by MidnightDesign** [comment]
Thank you for the quick response.

So there is no way to do it using the `StandardServer`?

**Comment by vladar** [comment]
We are in a bit different position than Apollo because the StandardServer supports two kinds of requests - PHP Globals and PSR-7 request. I guess the best thing you could do at the moment is to pass the `$request` separately into context closure (via ` use ($request)`).

In one of the future versions, we will deprecate PHP globals support and stick with PSR-7 to make it consistent.
