### ISSUE TITLE
How to get current query string inside a  resolver function

### ISSUE THREAD

**Issue by williamjieh** [webonyx/graphql-php#542]
Hi,
I want to get current query string inside a resolver function.
If there are multiple queries in this request, I want to get the current resolving query string, not the whole query string. Is it possible? Can I get it from `ResolveInfo` object ?
The reason for this is because I want to save this query string to somewhere and later use this query string to rerun this query.

Thank you!

**Comment by williamjieh** [comment]
The reason for get query string is because I want to save this query string in somewhere, and later run this query again .

**Comment by williamjieh** [comment]
I created a function to get current query string from `ResolveInfo` object:

```
  public function getCurrentQueryString($pathName, ResolveInfo $info) {
    $wholeQueryString = $info->operation->loc->source->body;

    /**
     * @var \GraphQL\Language\AST\NodeList $nodeList
     */
    $nodeList = $info->operation->selectionSet->selections;
    $count = $nodeList->count();

    for ($i = 0; $i < $count; $i++) {
      /**
       * @var \GraphQL\Language\AST\FieldNode $fieldNode
       */
      $fieldNode = $nodeList->offsetGet($i);
      
      if ($fieldNode->alias == NULL) {
        $name = $fieldNode->name->value;
      }
      else {
        $name = $fieldNode->alias->value;
      }

      if ($name == $pathName) {
        $start = $fieldNode->loc->start;
        $end = $fieldNode->loc->end;
        $subString = substr($wholeQueryString, $start, $end - $start);
        $currentQueryString = '{ ' . $subString . ' }';

        return $currentQueryString;
      }
    }

    return NULL;
  }
```
When call this function , pass two variables : $info->path[0] and $info , like this: 
`  getCurrentQueryString($info->path[0], $info);`

This is a temporary solution, I think there should be more better way to do this.

**Comment by vladar** [comment]
I am probably missing something. `Query string` term usually refers to the whole query string passed into `GraphQL::executeQuery()` as a 2nd argument.

But looks like you are trying to get something else. Can you provide an example of the whole query string and the part you want to retrieve? That would help.

**Comment by williamjieh** [comment]
Hi @vladar ,
Here is an example, the whole query string is like:
```
query {
  featured_books {
    bookTitle
    bookAuthor
    bookPrice
  }
  best_seller_books {
    bookTitle
    bookAuthor
    bookPrice
  }
}
```
I want to get `featured_books` sub query string and `best_seller_books` sub query string, inside each resolver function.

**Comment by vladar** [comment]
First, I don't think it is a good idea. GraphQL also has fragments, variables and include/skip directives so a client may send something like this:

```graphql
query ($includePrice: Bool) {
  featured_books {
    ...FeaturedBook
  }
  best_seller_books {
    bookTitle
    bookAuthor
    bookPrice @include(if: $includePrice)
  }
}

fragment FeaturedBook on Book {
    bookTitle
    bookAuthor
    bookPrice @include(if: $includePrice)
}
```

Different clients may send different fragment names, so if you rely on a string - you'll get a bunch of cache duplicates. Variables may also come into play, especially when fields have their own arguments.

Managing caching this way may become quite complicated. Usually, they fetch all the "small" fields in the resolver and cache them by entity id. "Heavy" fields (like nested objects or big texts/blobs) are always resolved separately.

But if you still want to go this route - try using `$info->getFieldSelection()`. It won't provide you a string but will return a list of all the requested sub-fields  for a given depth so that you could construct a cache key.

Alternatively, you could access the AST of the current field via `$info->fieldNodes` and re-construct the query.

See [description of the ResolveInfo class](https://webonyx.github.io/graphql-php/reference/#graphqltypedefinitionresolveinfo) in docs.
