### ISSUE TITLE
[Improvement idea] Allow custom extensions in error formatter

### ISSUE THREAD

**Issue by moufmouf** [webonyx/graphql-php#549]
Currently, if I want to add a custom field in the "extension" sections of an error, I must write a custom error formatter.

I believe it could be useful to allow users to add custom fields in the "extension" section.

Here is a proposal: we could create a new `CustomClientAware` interface that extends `ClientAware` and adds a `getExtensions` method. I'm not adding the `getExtensions` method to `ClientAware` in order to keep backward compatibility:

```php
interface CustomClientAware extends ClientAware {
    public function getExtensions(): array;
}
```

That would allow any exception to add custom fields in the extensions section (it can be a common need), very easily.

For instance:

```php
class ValidationException extends \Exception implements CustomClientAware
{
    // ...

    public function getExtensions(): array {
        return ['field' => $this->fieldName];
    }
}
```

This exception would generate:

```json
{
  "errors": [
    {
      "message" : "Invalid input",
      "extensions" : {
        "category": "validate",
        "field": "my_field"
      }
    }
  ]
}
```

I'm willing to work on a PR to add this feature if you think it is worthwhile. What do you think?

**Comment by simPod** [comment]
Personally I just extend Error in my application layer when I need something similar

```php
use GraphQL\Error\Error;

final class SomeErrorOrException extends Error
{
    ...

    public static function someNamedConstructor() : self
    {
        return new self(
            'Some message',
            null,
            null,
            null,
            null,
            null,
            ['extension name' => 'value']
        );
    }

    ...
```

IMO it's out of scope of this library.

**Comment by moufmouf** [comment]
Ho, I failed to see that you could use the `Error` exception to specify any extension. Thanks @simPod  for pointing that. That actually solves most of my problem.

:+1:

**Comment by vladar** [comment]
Glad you've figured it out.

**Comment by djibarian** [comment]
When upgrading from v14 to v15 had the problem of the extensions disappearing from the error returned array. After a lot of digging I noticed that there is a new interface `ProvidesExtensions` which can be used to implement a method `getExtensions()` which gives similar functionality.

I found that through the source code. I couldn't find any reference in the docs apart from the note "Remove error extension field category, use custom error formatting if you still need it" in 15.0.0 release notes, which of course is incorrect as there is no need to implement a custom formatter.

I spent half a day with this, so leaving the comment for others as a clue. Also wonder if this suggestion by @moufmouf has anything to do, because it looks very similar to the already implemented, despite looking being abandoned.

**Comment by spawnia** [comment]
> I found that through the source code. I couldn't find any reference in the docs apart from the note "Remove error extension field category, use custom error formatting if you still need it" in 15.0.0 release notes, which of course is incorrect as there is no need to implement a custom formatter.

It is indeed correct. `errors.*.extensions.category` is removed, but you may add it back with a custom formatter.

**Comment by djibarian** [comment]
Yes I meant *inaccurate*, not incorrect, sorry. Anyway, implementing a custom formatter doesn't look straightforward (at least looking at the docs) and the path of using the `ProvidesExtension` is much much simpler, but unfortunately undocumented.
