### ISSUE TITLE
Use & lazy load class names instead of full definition objects

### ISSUE THREAD

**Issue by rudiedirkx** [webonyx/graphql-php#55]
It seems very inefficient to load the entire schema for every query every time. I have a very small schema (5 types, 1 interface) and it takes 10 ms just to define the schema. Would it be possible to hint to class names instead of objects. This would also 'fix' the many `&$postType` references (and closures), because the objects are really lazy loaded.

I've no idea if this would be possible. It might have huge downsides. It definitely takes a lot of change. You might've tried something like this already.

Just to clarify, this is what it would look like (in my naive mind):

```
$schema = new Schema([
	'query' => QueryType::class,
	'types' => [
		UserType::class,
		CourtReservationType::class,
		ClassReservationType::class,
		PlayerType::class,
	],
]);
```

Schema or Executor or anyone could cache the objects by class name. All references would be class names:

```
'type' => Type::listOf(ReservationInterface::class),
```

```
'interfaces' => [ReservationInterface::class],
```

etc.

This would make the simple examples more complex, but reality simpler IMO. Every type would require a class, but not memory, until needed.

Like I said, no idea how feasible this is. Just a thought.

**Comment by vladar** [comment]
Right now query validation requires all types to be loaded in schema. 

I've been thinking about ways to relax this requirement, but it will have a price of some invalid queries passing through without errors on validation step and failing on execution step (ot not failing which may be even worse). 

So this will come at a cost, yet the payoff might worth it. I'll keep it open as it makes sense to investigate, but it might be not a simple change (at least from what I remember), so no promises on when it will be done. 

If you are interested, feel free to investigate this question further and post your findings / pull requests. 

The only note - I would not recommend passing class name of the type (because this way you are supposed to force class constructor signature, which is a bad idea).

Instead we should have TypeFactory in Schema which accepts type name (or any other type identifier) and returns type object.

In such case you can implement your own TypeFactory and use any type identifier as convinient for you. But default TypeFactory will be just a pass-through (expecting type instance) for backwards compatibility.

**Comment by smolinari** [comment]
I am not really in deep in this code or in GraphQL for that matter. I am only catching bits and pieces of concepts through the issues and lurking the repos of several GraphQL related libraries like this one. But, from what I understand, shouldn't query validation be more a development need, than a tool used at run-time for the entire program? I mean, couldn't you assume the developer, once he or she is finished with development, would have correct queries calling the server, which would mean the whole validation step could, at that point, be turned off?

Scott

**Comment by vladar** [comment]
@smolinari You can disable or you can keep it. Depends on your system. If all of your production queries are safe and you do not expose graphql endpoint to public then it makes sense to avoid validation, otherwise (e.g. you expose your graphql to 3rd parties) - you might want to keep it.

**Comment by smolinari** [comment]
Ah yes. That makes sense. I wasn't thinking about a public API.

I think this then goes back to our discussion about regular PHP's shared nothing architecture not being the best architecture for supporting and scaling a GraphQL server. 

Scott

**Comment by rudiedirkx** [comment]
Validation requires ALL types to be loaded? Even if the query only touches 3 types, and there are 20 in total? Necessary, or just the way it was built? All fields of all types too? So absolutely no point in lazy loading (closures) any part of it?

I'm trying a few things locally, but it's a lot harder than I hoped =)

**Comment by vladar** [comment]
@rudiedirkx at this point yes - this implementation mirrors JS reference implementation, but in order to make it work as you describe several significant modifications have to be made. I don't want to break connection with reference implementation until spec becomes stable. But at some point in time this will be done.

Yet if you find elegant way to do this - feel free to post your findings - we'll incorporate them into library code.

As for lazy loading of fields - sometimes it is just inevitable because your fields may reference the type that is not defined at the moment of field definition. So this `'fields'` closure is not really related to performance, yet it might help in future performance optimizations.

**Comment by vladar** [comment]
I close this in favor of #62. Feel free to re-open if you have any problems with proposed solution.
