### ISSUE TITLE
Add error to context from resolver

### ISSUE THREAD

**Issue by AndreasHeiberg** [webonyx/graphql-php#57]
Hi,

Say I have a query:

```
query GracefulFailure {
    user {
        nullableFieldWithFailure
        name
    }
}
```

```
{
    data: {
        user: {
            nullableFieldWithFailure: null
            name: 'Andreas'
        }
    },
    error: [
        {
            message: "Some error message provided by me",
            locations: [
                {
                    column: 3,
                    line: 2
                }
            ]
        }
    ]
}
```

It is my current understanding that the resolvers only get an array representation of the context. The context is therefore passed by value and adding an error to it will be pointless.

It seems like the suggested way of adding errors to a response is by throwing an exception in the resolver. The problem with this approach is that it would stop the query execution.

Is there currently a way to add a custom error from a resolver without stopping query execution?

Related issue: https://github.com/webonyx/graphql-php/issues/29

**Comment by vladar** [comment]
Throwing exception in resolver only stops query execution if the field type is marked as `non-null`. Otherwise (for nullable fields) error will be added to execution result and field value will be returned as `null`.

As for execution context - it is not passed to resolvers at all as it is executor implementation detail. Instead `GraphQL::executeAndReturnResult` returns instance of `GraphQL\Executor\ExecutionResult` which contains all errors generated, including your custom resolver exceptions (which should be available via `$executionResult->errors[$X]->getPrevious()`).

**Comment by vladar** [comment]
Closing this as it is not an issue. Feel free to reopen if I am missing something.
