### ISSUE TITLE
EnumType array value is not allowed

### ISSUE THREAD

**Issue by tpetry** [webonyx/graphql-php#599]
I don't know whether this is an implementation bug or just incorrect documentation.

The documentation for enum type's value entries is stating:
```
Type: mixed
Notes: Internal representation of enum item in your application (could be any value, including complex objects or callbacks)
```

But "any value" is incorrect as [arrays are not allowed](https://github.com/webonyx/graphql-php/blob/master/src/Type/Definition/EnumType.php#L103). If you pass in an array as value it's simply ignored and the name of the enum value is used instead. So it's basically everything **except** and array.

**Comment by vladar** [comment]
Array values should work in the full notation ([added a test](https://github.com/webonyx/graphql-php/commit/e7bef7c3be56ef35cea6c2f10006e0d596c06cc8) to verify):

```php
$episodeEnum = new EnumType([
    'name' => 'FooBarEnum',
    'values' => [
        'foo' => [
            'value' => ['foo', 'FOO'],
        ],
        'bar' => [
            'value' => ['bar', 'BAR'],
        ],
    ]
]);
```

But they won't work in a shorthand notation due to ambiguity:

```php
$episodeEnum = new EnumType([
    'name' => 'FooBarEnum',
    'values' => [
        'foo' => ['foo', 'FOO'],
        'bar' => ['bar', 'BAR'],
    ]
]);
```

The line in the code you've linked relates to the shorthand notation. If something doesn't work for you in the full notation - please provide an example?

**Comment by vladar** [comment]
Closing this but feel free to re-open if you think we should discuss it further.
