### ISSUE TITLE
Discuss: GraphQL Spec Compliance Tests

### ISSUE THREAD

**Issue by pranshuchittora** [webonyx/graphql-php#636]
**Edit**

##### Spec discussion  -> https://github.com/graphql/graphql-spec/issues/698
---
Hello maintainers
As a part of research around the simplifying graphql spec tests across implementations, I've stumbled upon the specs written here for `graphql-php`. I'd really appreciate if I can get an idea around how difficult it has been to maintain this test suite, and how often does it go out of parity with the actual graphql spec? Were there cases when misunderstanding the spec led to issues with the library?

**Would having a generic set of compatibility tests help around these issues if any?**

As schema definition in SDL format is natively supported by the library then it would be easy to adapt generic testing suite across different languages.

**Comment by vladar** [comment]
Hi @pranshuchittora 

Thanks for the proposal! It looks very promising. We basically replicate the test suite from `graphql-js`. It does have a significant maintenance cost so having a generic compatibility test suite would be awesome.

But we will start using it only if `graphql-js` switches to it as well. Because we mirror their implementation details and must be sure that our tests are equivalent to theirs.

That's also the reason why we didn't switch to graphql cats.

**Comment by pranshuchittora** [comment]
@vladar Hope you are safe and well.
Thanks for sharing your feedback and opinion. Would love to collaborate in implementing it once the organization accepts the proposal and GSoC starts :)

**Comment by vladar** [comment]
Sounds cool! I am closing this for now but feel free to re-open when we have something actionable.

**Comment by spawnia** [comment]
As part of the [GraphQL over HTTP Working Group](https://github.com/APIs-guru/graphql-over-http), a universal test for the HTTP aspect of GraphQL servers is being developed: https://github.com/jaydenseric/graphql-http-test

I plan to integrate that as it becomes available.
