### ISSUE TITLE
Extending types when parsing from type language doesn't work

### ISSUE THREAD

**Issue by xlttj** [webonyx/graphql-php#705]
I don't get extending types to work when building a schema from type language.

```php
<?php
$source = <<<GRAPHQL

type Query {
  foo: Boolean
}

extend type Query {
  bar: Boolean
}

extend type Query {
  baz: Boolean
}

schema {
  query: Query
}

GRAPHQL;

$schema = GraphQL\Utils\BuildSchema::build($source);
$fields = $schema->getQueryType()->getFields();
```

While $source seems to be considered valid, $schema contains only foo, while bar and baz are missing. What am I doing wrong here?

**Comment by spawnia** [comment]
This functionality is not implemented, but it should definitely be doable. We implement something like this ourselves in https://github.com/nuwave/lighthouse/blob/95bc697d4e000a705923fa285d961bc253332467/src/Schema/AST/ASTBuilder.php#L206

I think we will do something quite similar and merge on the AST level, since there is no runtime equivalent to https://github.com/webonyx/graphql-php/blob/master/src/Language/AST/ObjectTypeExtensionNode.php

There are some tricky bits to sort out which are not defined clearly (as far as i know).
- How to deal with duplicate or conflicting fields?
- How to deal deal with `extend scalar`?

**Comment by vladar** [comment]
We have SchemaExtender. Check out this comment on how to use it: https://github.com/webonyx/graphql-php/issues/180#issuecomment-444407411

And a PR for docs about it is more than welcome!

**Comment by vladar** [comment]
Closing this but feel free to re-open or continue the discussion if you have more questions.
