### ISSUE TITLE
Can i set throttle in mutation and query?

### ISSUE THREAD

**Issue by saeednikookalam** [webonyx/graphql-php#710]
Hi.
how set throttle in mutation and query in prevent to site down?

**Comment by spawnia** [comment]
Assuming you use some kind of framework, they usually provide middleware for throttling. Since GraphQL execution is inherently somewhat expensive - even just parsing the query - that should be your best bet.

This library provides facilities to limit expensive queries, see https://webonyx.github.io/graphql-php/security/
