### ISSUE TITLE
Clarification about Standard Server (complementary-tools)

### ISSUE THREAD

**Issue by illambo** [webonyx/graphql-php#753]
Hi, I would like to ask for clarification regarding the server standard.
I see that the major laravel packages (nuwave/lighthouse and rebing/graphql-laravel) that use this library as a core do not extend the standard server by default. 
I would like to understand if the standard server was born with the idea of ​​being able to be extended as a core in this sense (
I have read about [PSR-7 interface](http://webonyx.github.io/graphql-php/executing-queries/#using-server) for Laravel) or if it is just an example not suitable for production case.
Thanks and happy holidays

**Comment by spawnia** [comment]
As the maintainer of Lighthouse, I can tell you that we customize a big part of the request handling:
- file uploads
- dispatching internal events at different parts of the lifecycle
- error handling
- extensions

We do use some of the components within the `GraphQL\Server` namespace, they are quite useful. My impression was always that the `StandardServer` is just some glue code that puts it all together. It should work fine for simple use cases.

Maybe @vladar can chime in with his view. I am going to close this issue because it is not really actionable for further development.

**Comment by illambo** [comment]
Thanks for the reply.
