### ISSUE TITLE
Use https://github.com/thecodingmachine/safe

### ISSUE THREAD

**Issue by spawnia** [webonyx/graphql-php#893]
We deal with crude PHP functions quite a bit. Writing safe and correct code would be made much easier by using https://github.com/thecodingmachine/safe.

**Comment by simPod** [comment]
There are still some issues with static analysis (e.g. https://github.com/hectorj/safe-php-psalm-plugin/pull/5) because those functions are sometimes not affected 1:1 to SA tools updates. I'm not sure it's worth adding it as a dependency even though I've fixed/reported a lot of those issues and I use the library in my private projects.

**Comment by spawnia** [comment]
I think there is a lot of value in this library being zero-dependency. PHPStan makes some of the more insane defaults of native PHP functions bearable.
