### ISSUE TITLE
Instrumentation for performance metrics like Apollo Optics

### ISSUE THREAD

**Issue by adri** [webonyx/graphql-php#94]
Hi :) First of all, congrats to an awesome library.

I saw [Apollo Optics](https://optics.apollodata.com/) for performance monitoring. There are clients for [nodejs](url) and [ruby](https://github.com/apollographql/optics-agent-ruby), both based on the general [agent description](https://github.com/apollographql/optics-agent). 

When adding a PHP agent, I was wondering where would be a good place to hook into instrumentation. As far as I can see mostly a wrapper around field resolvers to time them would be handy.

Any ideas or tips how to add this instrumentation? 
PS: I'm not affiliated with Apollo.

**Comment by vladar** [comment]
Hey thanks!

I looked into node agent and it seems to modify original schema by looping through all fields and wrapping their resolvers with optics functions. Technically you can do the same with graphql-php schema. 

But on the other hand iterating over hundreds or thousands of fields is not the best way to do it in PHP. So it might make sense to provide hooks before/after field execution on library level.

PR for this feature is welcome!

If you decide to prepare such PR I suggest you to wrap [this call](https://github.com/webonyx/graphql-php/blob/master/src/Executor/Executor.php#L637-L644) with before and after callbacks and introduce static method on Executor to set these callbacks (like `setFieldHooks(callable $beforeResolve, callable $afterResolve)`).

Prefer static at this point because we may refactor executor later and it will be way easier to maintain backwards compatibility for simple static hooks. But if you have other opinion - I am open to discussion.

**Comment by vladar** [comment]
One more thing to keep in mind for your optics agent is that resolvers may return promises. So promiseAdapter must be also passed to hooks (in addition to other arguments) in order to check for `isThenable` and act appropriately.

**Comment by adri** [comment]
Thanks a lot for your input :) I think for now I don't have the time to work on this.
I might pick it up in a few months!

**Comment by jasonbahl** [comment]
@adri @vladar I've got Instrumentation setup for WPGraphQL. I've followed the proposed spec here: https://github.com/apollographql/apollo-tracing

You can see my implementation here: https://github.com/wp-graphql/wp-graphql-insights

It's super early (just worked on it a few days last week), but it follows the same approach as the node instrumentations I've seen where it wraps the entire schema. So far, I've not seen any noticeable performance differences with the tracing enabled vs disabled. . .but, I haven't done any significant testing. . .

I'm not sure what the best approach would be to create something that works for _any_ implementation of this library though. I'm making use of WordPress hooks/filters to accomplish my implementation. 

Feel free to use anything I've done in my implementation, or even make suggestions on how my implementation _could_ be better. 

Thanks!

**Comment by vladar** [comment]
For anyone interested, there is another proposal on how to enable apollo tracing for any existing schema: see https://github.com/webonyx/graphql-php/issues/289#issuecomment-399633709 PRs are welcome!
