### ISSUE TITLE
How interfaces work or how to get a few records?

### ISSUE THREAD

**Issue by Iscander1992** [webonyx/graphql-php#99]
Hello, I have a problem. My task is to get a record, using: 
```
{
    Records {
        id
    }
 }
```
I have written an interface and an entry point for getting the reply
```php
$testType = null;

        $interface = new InterfaceType([
            'name' => 'TestInterface',
            'fields' => function() use (&$interface) {
                return [
                    'id' => Type::nonNull(Type::string()),
                ];
            },
            'resolveType' => function ($obj) use (&$testType) {
                return $testType;
            },
        ]);

        $testType = new ObjectType([
            'name' => 'Test',
            'fields' => [
                'id' => new NonNull(Type::string()),
            ],
            'interfaces' => [$interface]
        ]);

        return new GraphQLSchema([
            'query' => new ObjectType([
                'name' => 'Query',
                'fields' => [
                    'Records' => [
                        'type' => Type::listOf($interface),
                        'resolve' => function ($entity, $args, $context, ResolveInfo $info) {
                            return [
                                [
                                    'id' => '1',
                                ],
                                [
                                    'id' => '2',
                                ],
                                [
                                    'id' => '3',
                                ]
                            ];
                        },
                    ],
                ],
            ]),
        ]);
```
And I have got such errors: 
```
{
  "data": {
    "Records": [
      null,
      null
    ]
  },
  "errors": [
    {
      "message": "Could not find possible implementing types for $TestInterface in schema. Check that schema.types is defined and is an array of all possible types in the schema.",
      "locations": [
        {
          "line": 2,
          "column": 17
        }
      ],
      "path": [
        "Records",
        0
      ]
    },
    {
      "message": "Could not find possible implementing types for $TestInterface in schema. Check that schema.types is defined and is an array of all possible types in the schema.",
      "locations": [
        {
          "line": 2,
          "column": 17
        }
      ],
      "path": [
        "Records",
        1
      ]
    }
  ]
}
```
Why did it happen?

**Comment by vladar** [comment]
It is known problem (with known solutions). I'll walk you through the process of type registration in schema to provide an overview...

When you create schema what happens is graphql-php scans all fields and all nested types from the very root to all leafs.

The problem is that while traversing this tree of types GraphQL only sees field `Record` with type `TestInterface`. That's the only visible types in your schema.

Unfortunately this data is not enough to figure out that you have other types as implementations of `TestInterface`, hence the error you see. It happens with object types which only show up in schema as implementation of some interface and are not referenced anywhere else.

So your options:
1. Add field anywhere in schema of your `Test` type (e.g. in Query or other visible object type)
2. Pass such "invisible" types in special option `types` of schema constructor. 

So in your example option 2 would look like this:
```php
new GraphQLSchema([
    'query' => ...,
    'types' => [$testType]
]);
```

This problem is common to most graphql implementations, including graphql-js.

**Comment by Iscander1992** [comment]
Thank you very much. It works.

**Comment by 01e9** [comment]
> @vladar https://github.com/webonyx/graphql-php/issues/99#issuecomment-287439086

PLEASE document this problem here https://webonyx.github.io/graphql-php/type-system/interfaces/

I've spent 3 hours today debugging api-platform and graphql-php to understand why my interface based types are missing in schema. _Luckily I found this comment._
